#define MAINPREFIX z
#define PREFIX tis

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR  MAJOR,MINOR,PATCH

#define REQUIRED_VERSION 2.20
#define REQUIRED_CBA_VERSION {3,18,3}

#define COMPONENT_NAME QUOTE(COMPONENT)
