name = "TIS-Medical"
prefix = "tis_medical"
mainprefix = "z"

[properties]
author = "TIS-Team"
url = "https://github.com/TIS-Team/TIS-Medical"

[version]
path = "addons/main/script_version.hpp"
git_hash = 8

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "keys/**"
]
exclude = [
    ".idea/**"
]

[lints.sqf]
command_case = true
